name: Delete Branch on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          # Extract branch name from the pull request URL
          BRANCH_NAME=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/\//%2F/g')

          # Delete the branch
          git push origin --delete "${BRANCH_NAME}"
